import {
  useState,
  useRef,
  useEffect,
  useTransition,
  type ReactNode,
} from "react"

import { useTheme } from "@/components/theme-provider"
import { computeDiff, type DiffResponse, type DiffHunk } from "@/lib/api"

// ── Hook ────────────────────────────────────────────────────────

type DiffState =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "done"; data: DiffResponse }
  | { status: "error"; message: string }

function useDiff(
  params:
    | {
        mode: "contents"
        fileName: string
        oldContent: string
        newContent: string
      }
    | { mode: "patch"; patch: string }
): DiffState {
  const { resolvedTheme } = useTheme()
  const theme = resolvedTheme === "light" ? "light" : "dark"

  // Destructure to stable primitives for dependency arrays
  const mode = params.mode
  const fileName = mode === "contents" ? params.fileName : ""
  const oldContent = mode === "contents" ? params.oldContent : ""
  const newContent = mode === "contents" ? params.newContent : ""
  const patch = mode === "patch" ? params.patch : ""

  const [state, setState] = useState<DiffState>({ status: "idle" })

  useEffect(() => {
    setState({ status: "loading" })

    let cancelled = false

    const body =
      mode === "contents"
        ? {
            mode: "contents" as const,
            file_name: fileName,
            old_content: oldContent,
            new_content: newContent,
            theme,
          }
        : { mode: "patch" as const, patch, theme }

    computeDiff(body)
      .then((data) => {
        if (cancelled) return
        setState({ status: "done", data })
      })
      .catch((err: unknown) => {
        if (cancelled) return
        setState({
          status: "error",
          message: err instanceof Error ? err.message : "Diff failed",
        })
      })

    return () => {
      cancelled = true
    }
  }, [mode, fileName, oldContent, newContent, patch, theme])

  return state
}

// ── Deferred render ─────────────────────────────────────────────

function useDeferredRender() {
  const [shouldRender, setShouldRender] = useState(false)
  const [isPending, startTransition] = useTransition()
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const element = ref.current
    if (!element) return

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0]?.isIntersecting) {
          startTransition(() => {
            setShouldRender(true)
          })
          observer.disconnect()
        }
      },
      { rootMargin: "200px" }
    )

    observer.observe(element)
    return () => observer.disconnect()
  }, [])

  return { ref, shouldRender, isPending }
}

function DeferredDiffContainer({ children }: { children: ReactNode }) {
  const { ref, shouldRender, isPending } = useDeferredRender()

  return (
    <div ref={ref} className="tool-timeline-patch-diff-container">
      {shouldRender ? (
        children
      ) : (
        <div
          className="tool-timeline-patch-diff-placeholder"
          aria-hidden="true"
        >
          {isPending ? "Loading..." : ""}
        </div>
      )}
    </div>
  )
}

// ── Diff output rendering ───────────────────────────────────────

function DiffScrollContainer({ children }: { children: ReactNode }) {
  return (
    <div className="tool-timeline-pierre-virtualizer">
      <div className="tool-timeline-pierre-virtualizer-content">{children}</div>
    </div>
  )
}

function DiffOutput({
  data,
  mode,
}: {
  data: DiffResponse
  mode: "unified" | "split"
}) {
  if (mode === "split") {
    return <SplitDiffOutput hunks={data.hunks} />
  }
  return <UnifiedDiffOutput hunks={data.hunks} />
}

function UnifiedDiffOutput({ hunks }: { hunks: DiffHunk[] }) {
  return (
    <div className="server-diff-unified">
      {hunks.map((hunk, hi) => (
        <div key={hi} className="server-diff-hunk">
          <div className="server-diff-hunk-header">
            @@ -{hunk.old_start},{hunk.old_count} +{hunk.new_start},
            {hunk.new_count} @@
          </div>
          {hunk.lines.map((line, li) => (
            <div key={li} className="server-diff-line" data-kind={line.kind}>
              <span className="server-diff-ln server-diff-ln-old">
                {line.old_ln ?? ""}
              </span>
              <span className="server-diff-ln server-diff-ln-new">
                {line.new_ln ?? ""}
              </span>
              <span className="server-diff-indicator">
                {line.kind === "add" ? "+" : line.kind === "del" ? "-" : " "}
              </span>
              {/* HTML generated by our Rust backend syntect, not user input */}
              <span
                className="server-diff-content"
                dangerouslySetInnerHTML={{ __html: line.html }}
              />
            </div>
          ))}
        </div>
      ))}
    </div>
  )
}

function SplitDiffOutput({ hunks }: { hunks: DiffHunk[] }) {
  return (
    <div className="server-diff-split">
      {hunks.map((hunk, hi) => {
        const pairs = buildSplitPairs(hunk)
        return (
          <div key={hi} className="server-diff-hunk">
            <div className="server-diff-hunk-header">
              @@ -{hunk.old_start},{hunk.old_count} +{hunk.new_start},
              {hunk.new_count} @@
            </div>
            {pairs.map((pair, pi) => (
              <div key={pi} className="server-diff-split-row">
                <div
                  className="server-diff-split-cell server-diff-split-left"
                  data-kind={pair.left?.kind ?? "empty"}
                >
                  <span className="server-diff-ln">
                    {pair.left?.old_ln ?? ""}
                  </span>
                  <span className="server-diff-indicator">
                    {pair.left?.kind === "del" ? "-" : pair.left ? " " : ""}
                  </span>
                  {pair.left ? (
                    <span
                      className="server-diff-content"
                      dangerouslySetInnerHTML={{ __html: pair.left.html }}
                    />
                  ) : (
                    <span className="server-diff-content" />
                  )}
                </div>
                <div
                  className="server-diff-split-cell server-diff-split-right"
                  data-kind={pair.right?.kind ?? "empty"}
                >
                  <span className="server-diff-ln">
                    {pair.right?.new_ln ?? ""}
                  </span>
                  <span className="server-diff-indicator">
                    {pair.right?.kind === "add" ? "+" : pair.right ? " " : ""}
                  </span>
                  {pair.right ? (
                    <span
                      className="server-diff-content"
                      dangerouslySetInnerHTML={{ __html: pair.right.html }}
                    />
                  ) : (
                    <span className="server-diff-content" />
                  )}
                </div>
              </div>
            ))}
          </div>
        )
      })}
    </div>
  )
}

type SplitPair = {
  left: { kind: string; old_ln?: number; html: string } | null
  right: { kind: string; new_ln?: number; html: string } | null
}

function buildSplitPairs(hunk: DiffHunk): SplitPair[] {
  const pairs: SplitPair[] = []
  const lines = hunk.lines

  let i = 0
  while (i < lines.length) {
    const line = lines[i]!

    if (line.kind === "ctx") {
      pairs.push({
        left: { kind: "ctx", old_ln: line.old_ln, html: line.html },
        right: { kind: "ctx", new_ln: line.new_ln, html: line.html },
      })
      i++
      continue
    }

    // Collect consecutive del/add runs and pair them
    const dels: typeof lines = []
    const adds: typeof lines = []

    while (i < lines.length && lines[i]!.kind === "del") {
      dels.push(lines[i]!)
      i++
    }
    while (i < lines.length && lines[i]!.kind === "add") {
      adds.push(lines[i]!)
      i++
    }

    const maxLen = Math.max(dels.length, adds.length)
    for (let j = 0; j < maxLen; j++) {
      const del = dels[j]
      const add = adds[j]
      pairs.push({
        left: del ? { kind: "del", old_ln: del.old_ln, html: del.html } : null,
        right: add ? { kind: "add", new_ln: add.new_ln, html: add.html } : null,
      })
    }
  }

  return pairs
}

// ── Loading / Error states ──────────────────────────────────────

function DiffLoading() {
  return (
    <div className="server-diff-status" data-state="loading">
      <span className="shimmer-text">Computing diff…</span>
    </div>
  )
}

function DiffError({ message }: { message: string }) {
  return (
    <div className="server-diff-status" data-state="error">
      {message}
    </div>
  )
}

// ── Exported components ─────────────────────────────────────────

export function ServerPatchDiffOutput({ patch }: { patch: string }) {
  const state = useDiff({ mode: "patch", patch })

  return (
    <div className="tool-timeline-pierre-root tool-timeline-pierre-root-patch">
      <DiffScrollContainer>
        {state.status === "loading" || state.status === "idle" ? (
          <DiffLoading />
        ) : state.status === "error" ? (
          <DiffError message={state.message} />
        ) : (
          <DiffOutput data={state.data} mode="unified" />
        )}
      </DiffScrollContainer>
    </div>
  )
}

export function DeferredServerPatchDiffOutput({ patch }: { patch: string }) {
  return (
    <DeferredDiffContainer>
      <ServerPatchDiffOutput patch={patch} />
    </DeferredDiffContainer>
  )
}

export function ServerMultiFileDiffOutput({
  fileName,
  oldContent,
  newContent,
  diffStyle,
}: {
  fileName: string
  oldContent: string
  newContent: string
  diffStyle: "unified" | "split"
}) {
  const state = useDiff({
    mode: "contents",
    fileName,
    oldContent,
    newContent,
  })

  return (
    <div className="tool-timeline-pierre-root tool-timeline-pierre-root-multi">
      <DiffScrollContainer>
        {state.status === "loading" || state.status === "idle" ? (
          <DiffLoading />
        ) : state.status === "error" ? (
          <DiffError message={state.message} />
        ) : (
          <DiffOutput data={state.data} mode={diffStyle} />
        )}
      </DiffScrollContainer>
    </div>
  )
}

export function DeferredServerMultiFileDiffOutput({
  fileName,
  oldContent,
  newContent,
  diffStyle,
}: {
  fileName: string
  oldContent: string
  newContent: string
  diffStyle: "unified" | "split"
}) {
  return (
    <DeferredDiffContainer>
      <ServerMultiFileDiffOutput
        fileName={fileName}
        oldContent={oldContent}
        newContent={newContent}
        diffStyle={diffStyle}
      />
    </DeferredDiffContainer>
  )
}
