import {
  useState,
  useRef,
  useEffect,
  useTransition,
  type ReactNode,
} from "react"

import { useTheme } from "@/components/theme-provider"
import {
  computeDiff,
  type DiffResponse,
  type DiffHunk,
  type SplitPair,
} from "@/lib/api"

// ── Hook ────────────────────────────────────────────────────────

type DiffState =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "done"; data: DiffResponse }
  | { status: "error"; message: string }

function useDiff(
  params:
    | {
        mode: "contents"
        fileName: string
        oldContent: string
        newContent: string
        style: "unified" | "split"
      }
    | { mode: "patch"; patch: string }
): DiffState {
  const { resolvedTheme } = useTheme()
  const theme = resolvedTheme === "light" ? "light" : "dark"

  const mode = params.mode
  const fileName = mode === "contents" ? params.fileName : ""
  const oldContent = mode === "contents" ? params.oldContent : ""
  const newContent = mode === "contents" ? params.newContent : ""
  const style = mode === "contents" ? params.style : "unified"
  const patch = mode === "patch" ? params.patch : ""

  const [state, setState] = useState<DiffState>({ status: "idle" })

  useEffect(() => {
    setState({ status: "loading" })

    let cancelled = false

    const body =
      mode === "contents"
        ? {
            mode: "contents" as const,
            file_name: fileName,
            old_content: oldContent,
            new_content: newContent,
            theme,
            style,
          }
        : { mode: "patch" as const, patch, theme }

    computeDiff(body)
      .then((data) => {
        if (cancelled) return
        setState({ status: "done", data })
      })
      .catch((err: unknown) => {
        if (cancelled) return
        setState({
          status: "error",
          message: err instanceof Error ? err.message : "Diff failed",
        })
      })

    return () => {
      cancelled = true
    }
  }, [mode, fileName, oldContent, newContent, patch, theme, style])

  return state
}

// ── Deferred render ─────────────────────────────────────────────

function useDeferredRender() {
  const [shouldRender, setShouldRender] = useState(false)
  const [isPending, startTransition] = useTransition()
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const element = ref.current
    if (!element) return

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0]?.isIntersecting) {
          startTransition(() => {
            setShouldRender(true)
          })
          observer.disconnect()
        }
      },
      { rootMargin: "200px" }
    )

    observer.observe(element)
    return () => observer.disconnect()
  }, [])

  return { ref, shouldRender, isPending }
}

function DeferredDiffContainer({ children }: { children: ReactNode }) {
  const { ref, shouldRender, isPending } = useDeferredRender()

  return (
    <div ref={ref} className="tool-timeline-patch-diff-container">
      {shouldRender ? (
        children
      ) : (
        <div
          className="tool-timeline-patch-diff-placeholder"
          aria-hidden="true"
        >
          {isPending ? "Loading..." : ""}
        </div>
      )}
    </div>
  )
}

// ── Shared sub-components ───────────────────────────────────────

function DiffScrollContainer({ children }: { children: ReactNode }) {
  return (
    <div className="tool-timeline-pierre-virtualizer">
      <div className="tool-timeline-pierre-virtualizer-content">{children}</div>
    </div>
  )
}

function HunkHeader({ hunk }: { hunk: DiffHunk }) {
  return (
    <div className="sd-hunk-header">
      <span>
        @@ -{hunk.old_start},{hunk.old_count} +{hunk.new_start},{hunk.new_count}{" "}
        @@
      </span>
    </div>
  )
}

// ── Unified view ────────────────────────────────────────────────

function UnifiedDiffOutput({ hunks }: { hunks: DiffHunk[] }) {
  return (
    <div className="sd-table sd-unified">
      {hunks.map((hunk, hi) => (
        <div key={hi} className="sd-hunk">
          <HunkHeader hunk={hunk} />
          {hunk.lines.map((line, li) => (
            <div key={li} className="sd-row" data-kind={line.kind}>
              <div className="sd-bar" />
              <span className="sd-ln">{line.old_ln ?? ""}</span>
              <span className="sd-ln">{line.new_ln ?? ""}</span>
              {/* HTML generated by our Rust backend syntect, not user input */}
              <span
                className="sd-code"
                dangerouslySetInnerHTML={{ __html: line.html }}
              />
            </div>
          ))}
        </div>
      ))}
    </div>
  )
}

// ── Split view ──────────────────────────────────────────────────

function SplitDiffOutput({ hunks }: { hunks: DiffHunk[] }) {
  return (
    <div className="sd-table sd-split">
      {hunks.map((hunk, hi) => {
        const pairs = hunk.split_pairs ?? []
        return (
          <div key={hi} className="sd-hunk">
            <HunkHeader hunk={hunk} />
            {pairs.map((pair: SplitPair, pi: number) => (
              <div key={pi} className="sd-split-row">
                {/* Left (old) */}
                <div
                  className="sd-split-cell"
                  data-kind={pair.left?.kind ?? "empty"}
                  data-side="old"
                >
                  <div className="sd-bar" />
                  <span className="sd-ln">{pair.left?.ln ?? ""}</span>
                  {pair.left ? (
                    <span
                      className="sd-code"
                      dangerouslySetInnerHTML={{ __html: pair.left.html }}
                    />
                  ) : (
                    <span className="sd-code" />
                  )}
                </div>
                {/* Right (new) */}
                <div
                  className="sd-split-cell"
                  data-kind={pair.right?.kind ?? "empty"}
                  data-side="new"
                >
                  <div className="sd-bar" />
                  <span className="sd-ln">{pair.right?.ln ?? ""}</span>
                  {pair.right ? (
                    <span
                      className="sd-code"
                      dangerouslySetInnerHTML={{ __html: pair.right.html }}
                    />
                  ) : (
                    <span className="sd-code" />
                  )}
                </div>
              </div>
            ))}
          </div>
        )
      })}
    </div>
  )
}

// ── Dispatch ────────────────────────────────────────────────────

function DiffOutput({
  data,
  mode,
}: {
  data: DiffResponse
  mode: "unified" | "split"
}) {
  if (mode === "split") {
    return <SplitDiffOutput hunks={data.hunks} />
  }
  return <UnifiedDiffOutput hunks={data.hunks} />
}

// ── Loading / Error ─────────────────────────────────────────────

function DiffLoading() {
  return (
    <div className="sd-status" data-state="loading">
      <span className="shimmer-text">Computing diff…</span>
    </div>
  )
}

function DiffError({ message }: { message: string }) {
  return (
    <div className="sd-status" data-state="error">
      {message}
    </div>
  )
}

// ── Exported components ─────────────────────────────────────────

export function ServerPatchDiffOutput({ patch }: { patch: string }) {
  const state = useDiff({ mode: "patch", patch })

  return (
    <div className="tool-timeline-pierre-root tool-timeline-pierre-root-patch">
      <DiffScrollContainer>
        {state.status === "loading" || state.status === "idle" ? (
          <DiffLoading />
        ) : state.status === "error" ? (
          <DiffError message={state.message} />
        ) : (
          <DiffOutput data={state.data} mode="unified" />
        )}
      </DiffScrollContainer>
    </div>
  )
}

export function DeferredServerPatchDiffOutput({ patch }: { patch: string }) {
  return (
    <DeferredDiffContainer>
      <ServerPatchDiffOutput patch={patch} />
    </DeferredDiffContainer>
  )
}

export function ServerMultiFileDiffOutput({
  fileName,
  oldContent,
  newContent,
  diffStyle,
}: {
  fileName: string
  oldContent: string
  newContent: string
  diffStyle: "unified" | "split"
}) {
  const state = useDiff({
    mode: "contents",
    fileName,
    oldContent,
    newContent,
    style: diffStyle,
  })

  return (
    <div className="tool-timeline-pierre-root tool-timeline-pierre-root-multi">
      <DiffScrollContainer>
        {state.status === "loading" || state.status === "idle" ? (
          <DiffLoading />
        ) : state.status === "error" ? (
          <DiffError message={state.message} />
        ) : (
          <DiffOutput data={state.data} mode={diffStyle} />
        )}
      </DiffScrollContainer>
    </div>
  )
}

export function DeferredServerMultiFileDiffOutput({
  fileName,
  oldContent,
  newContent,
  diffStyle,
}: {
  fileName: string
  oldContent: string
  newContent: string
  diffStyle: "unified" | "split"
}) {
  return (
    <DeferredDiffContainer>
      <ServerMultiFileDiffOutput
        fileName={fileName}
        oldContent={oldContent}
        newContent={newContent}
        diffStyle={diffStyle}
      />
    </DeferredDiffContainer>
  )
}
